file(GLOB Sources
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/alignment_gap_between.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/attribute_name.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/attribute_set.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/attribute_set_impl.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/attribute_value_set.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/code_conversion.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/core.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/date_time_format_parser.cpp
  #${PROJECT_SOURCE_DIR}/dependencies/log/src/debug_output_backend.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/default_attribute_names.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/default_filter_factory.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/default_filter_factory.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/default_formatter_factory.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/default_formatter_factory.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/default_sink.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/default_sink.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/dump_avx2.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/dump.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/dump_ssse3.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/event.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/event_log_backend.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/event_log_registry.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/exceptions.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/filter_parser.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/format_parser.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/formatter_parser.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/global_logger_storage.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/id_formatting.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/init_from_settings.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/init_from_stream.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/light_rw_mutex.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/matches_relation_factory.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/named_scope.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/named_scope_format_parser.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/once_block.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/parser_utils.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/parser_utils.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/process_id.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/process_name.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/record_ostream.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/settings_parser.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/severity_level.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/spirit_encoding.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/spirit_encoding.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/stateless_allocator.hpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/syslog_backend.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/text_file_backend.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/text_multifile_backend.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/text_ostream_backend.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/thread_id.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/threadsafe_queue.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/thread_specific.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/timer.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/timestamp.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/trivial.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/unhandled_exception_count.cpp
  ${PROJECT_SOURCE_DIR}/dependencies/log/src/unique_ptr.hpp
)
include_directories(${PROJECT_SOURCE_DIR}/dependencies/log/include)
add_library(boostlog ${Sources})
